spring.application.name=artlux

# Enable the H2 console
spring.h2.console.enabled=true
# (Optional) Change the path from default /h2-console
spring.h2.console.path=/h2-console

# o spring salva o banco em um arquivo ao invés da RAM
spring.datasource.url=jdbc:h2:file:./banco_artlux

# definindo um usuario e senha
spring.datasource.username=admin
spring.datasource.password=1234

# atualiza o banco de dados conforme as mudanças, sem apagar dados antigos
spring.jpa.hibernate.ddl-auto=update